import Head from 'next/head'
import Image from 'next/image'
import Features from '../components/Features'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gray' >
         <Features />
      </main>
    </div>
  )
}
